### ISSUE TITLE
🛠️ Add `@radix-ui/*` to dependabot merge groups

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10818]
## 🛠️ Tooling

Make a merge group for our radix depenendencies.

## 🕵️ Details

These dependencies are all related and usually come in groups, would be nice to have them all bumped at the same time.

## 🙋‍♀️ Proposed Solution

Add the following to `dependabot.yml`

```yml
      radix:
        patterns:
          - "@radix-ui*"
        update-types:
          - "major"
          - "minor"
          - "patch"
```

## ✅ Acceptance Criteria

- [ ] All radix dependencies caught in a merge group
