### ISSUE TITLE
Spike- How do we handle lots of Dependabot PR's when each PR runs many Actions

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1768]
# Description
With more and more Github Actions running on each PR (tests, Chromatic, bundle size, etc) each PR takes several minutes to run. And Depandabot makes a *lot* of PRs for us.

**Comment by tristan-orourke** [comment]
Thoughts:
- run updates manually
- Monitor for vulnerabilities instead of all updates (eg Snyk)
- Use _another_ action to bundle dependency updates

**Comment by patcon** [comment]
- eventual merging of react apps might make dependabot less painful
- we can turn some off for dependabot, but I've found them all helpful (though I usually arrived the next morning and didn't find myself waiting on them)
- since many dependabot PRs auto-rebase as others get merged, a good practice might be to review all PRs first (using status checks to guide), then merge them in one go after all reviews are complete :)

**Comment by patcon** [comment]
One more alternative: Everyone could stop using GitHub's "watch" button and instead use a workflow to mention people, excluding dependabot PRs. Perk = potential for more fine-grained control of notifications.

(Assumption: If the beef is more with noisy notifications for dependabot, rather than individually updated deps with per-package tests/checks.)

```yml
# .github/workflows/watch.yml
name: Watch repo
on:
  pull_request_target:
    types: [ "opened" ]
    branches-ignore: [ "dependabot/**" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Notify team
        uses: JoseThen/comment-pr@v1.1.1
        with:
          # @org/team mention won't work unless using someone's PERSONAL_ACCESS_TOKEN as token.
          comment: |
            👃👈 boop @person1 @person2 @person3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
