### ISSUE TITLE
Fix math errors during minification in prod build

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3801]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

Warning is showing up on mainline during the prod build (but it's not failing the build, which is presumably ok).

We don't notice it in local builds because `npm run dev` generates hydrogen.css, but doesn't check whether it's valid, so no error there.

`npm run production` tries to minify hydrogen.css, and notices that some of the `calc`  CSS math is malformed. It throws a warning, not an error, so we didn't notice readily.

Example of warning: 

There are two types and 4 warnings total, both of which result from calculations on "none".

1. `none + (calc((1 * var(--h2-base-whitespace)) * 1rem) * 2)` variations
2. `none + (0px * 2)`

See here for error log: https://github.com/GCTC-NTGC/gc-digital-talent/runs/8097783243?check_suite_focus=true#step:7:66

I've unminified the production hydrogen.css to make it easier to debug:

1. https://gist.github.com/patcon/a8816a70fef661754f92e2433437d5d7#file-hydrogen-max-css-L941
   
    ```css
    [data-h2] [data-h2-container*="base(center, full, x1)"] {
        margin-right: auto;
        margin-left: auto;
        max-width: calc(none + (calc((1 * var(--h2-base-whitespace)) * 1rem) * 2));
        padding-right: calc((1 * var(--h2-base-whitespace)) * 1rem);
        padding-left: calc((1 * var(--h2-base-whitespace)) * 1rem);
        width: 100%
    }
    ```
2. https://gist.github.com/patcon/a8816a70fef661754f92e2433437d5d7#file-hydrogen-max-css-L3500
   
    ```css
    [data-h2] [data-h2-container*="p-tablet(center, full, x2)"] {
        margin-right: auto;
        margin-left: auto;
        max-width: calc(none + (calc((2 * var(--h2-base-whitespace)) * 1rem) * 2));
        padding-right: calc((2 * var(--h2-base-whitespace)) * 1rem);
        padding-left: calc((2 * var(--h2-base-whitespace)) * 1rem);
        width: 100%
    }
    ```
3. https://gist.github.com/patcon/a8816a70fef661754f92e2433437d5d7#file-hydrogen-max-css-L896
   
    ```css
    [data-h2] [data-h2-container*="base(center, full, x2)"] {
        margin-right: auto;
        margin-left: auto;
        max-width: calc(none + (calc((2 * var(--h2-base-whitespace)) * 1rem) * 2));
        padding-right: calc((2 * var(--h2-base-whitespace)) * 1rem);
        padding-left: calc((2 * var(--h2-base-whitespace)) * 1rem);
        width: 100%
    }
    ```
1. https://gist.github.com/patcon/a8816a70fef661754f92e2433437d5d7#file-hydrogen-max-css-L959
   
    ```css
    [data-h2] [data-h2-container*="base(center, full, 0)"] {
        margin-right: auto;
        margin-left: auto;
        max-width: calc(none + (0px * 2));
        padding-right: 0px;
        padding-left: 0px;
        width: 100%
    }
    ```

Potential followup tasks?
- Our project could lint hydrogen CSS to see if it's valid? Or Hydrogen itself could? cc @JoshBeveridge 

**Urgency:** Not blocking, but may cause CSS to look differently in prod than it does in development if minification tool is stripping something malformed that is otherwise being attempted to render in browser. 🤷 

## Acceptance Criteria
- [ ] `npm run production --workspaces` builds without warnings

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap
