### ISSUE TITLE
Look into Local Load Testing

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4458]
We need to think about Load Testing!

How many simultaneous requests will our prod server be able to handle? (And how many should we expect per person, given all the requests for resource files and api calls per page.) Will our API queries slow to a crawl with many concurrent users?

The scope of this spike is local load testing only.  Our Azure testing spike is #5554 

## :question: Spike Questions?
- What tools would we need to do load testing?
- Are there other teams in gov we can ask about similar experiences?
- Can we generate large amounts of accurate-ish data first, to ensure that doesn't bog down our DB queries too much?

## 📦️ Timebox
1 day

**Comment by petertgiles** [comment]
Since our site is an SPA it's just some basic static file serving.  I'm guessing we're first going to run into trouble with the API and database.

Some issues I opened about that:
#4184
#4185

**Comment by patcon** [comment]
Example of how locust was used for another project I'm adjacent to: https://github.com/joshsmith2/polis-loadtesting

**Comment by petertgiles** [comment]
Split into IMTD load testing and more focused app load testing

**Comment by esizer** [comment]
Not super clear on this but I messed around with locust for a few mins and it seemed pretty easy to setup. 

## Minimal Setup

```python
#./locust.py
import time
from locust import HttpUser, task, between

class TestUser(HttpUser):
    host = "http://webserver"
    wait_time = between(1, 5)

    @task
    def home(self):
        self.client.get("/en")
```

```yml
services:
  # ...
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locust.py --master -H http://webserver:8080
 ```
 
 ## Results

![Screenshot 2023-12-21 143221](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/cfec1c86-59f2-44e9-ac02-e1404a26483c)
