### ISSUE TITLE
✏️ Encourage users with questions to use discussions

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6184]
## ✏️ Documentation

This would update the issue [template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) to provide a link to GitHub discussions in order to encourage users to use discussions for questions rather than issues.

## 🙋‍♀️ Proposed Changes

1. Create `.github/config.yml`
```
blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/GCTC-NTGC/gc-digital-talent/discussions
    about: Ask questions and discuss with other community members
```
2. Delete `.github/ISSUE_TEMPLATE/❓-question.md` file
3. Delete contents of `.github/issue_template.yml` file or add `blank_issues_enabled: false` to `.github/config.yml`

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the documentation has been added/updated appropriately.

- [ ] commit to main and visit https://github.com/GCTC-NTGC/gc-digital-talent/issues/new/choose
